- name: install nginx s/w
  hosts: web
  become: yes
  tasks:
  - name: install the ngnix software
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: run ngnix
    ansible.builtin.service:
      name: nginx
      state: prasent