- name: install nginx s/w
  hosts: web
  become: yes
  tasks:
  - name: install s/w
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx 
    ansible.bulitin.package:
      name: nginx
      state: started
      enabled: yes