- name: install ngnix
  hosts: web
  become: yes
  tasks:
  - name: install ignix
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run ignix
    ansiblee.builtin.service:
      name: nginx
      state: started
      enabled: yes