- name: Print the course detais
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the details
    ansible.builtin.debug:
      msg: "Hi, I am choosing {{COURSE}} duration will be {{DURATION}} and trainer {{TRAINER}} for better carrier"