- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible-facts }}"

  - name: install nginx if radhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RadHat"

  - name: install nginx if ubuntu
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"