- name: demo on loops
  hosts: local
  connection: local
  tasks:
    - name: print users
      ansible.builtin.debug:
        msg: " hello {{ item }} welcome to my home"
      loop:
      - ramesh
      - uday
      - suresh
      - durga