- name: installing packages by using loops concept
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: installing below packages
      ansible.builtin.package:
        name : "{{ item }}"
        state: present
      loop:
      - nginx
      - mysql
      - postfix
      - httpd